### ISSUE TITLE
Unable to build examples with current repo update

### ISSUE THREAD

**Issue by prashantrar** [VectorBlox/mxp#2]
I tried building the examples for zedboard arm standalone but im getting this error. My PROJ_ROOT is defined properly, and i have sdk, vivado and all other tools working.

P.S.:- The older version of the repo is working

Invoking: gcc compiler
arm-xilinx-eabi-gcc -Wall -c -fmessage-length=0 -DUSE_ZYNQ_UART  -O3 -I/home/prashant014/My_MXP/mxp/examples/boards/zedboard_arm_viv/prebuilt_zedboard_arm_viv_v16/bsp/ps7_cortexa9_0/include  \
    -MD -o"obj/arm-xilinx-eabi-gcc/vbw_rgb2luma16.o" "vbw_rgb2luma16.c"
In file included from vbw_rgb2luma16.c:42:0:
/home/prashant014/My_MXP/mxp/examples/boards/zedboard_arm_viv/prebuilt_zedboard_arm_viv_v16/bsp/ps7_cortexa9_0/include/vbx.h:99:2: error: #error Must define one of ARM_XIL_STANDALONE, ARM_XIL_LINUX, ARM_ALT_STANDALONE, MB_STANDALONE, NIOS_STANDALONE, VBX_SIMULATOR
 #error Must define one of ARM_XIL_STANDALONE, ARM_XIL_LINUX, ARM_ALT_STANDALONE, MB_STANDALONE, NIOS_STANDALONE, VBX_SIMULATOR
  ^
../../common/xil_lib.mk:22: recipe for target 'obj/arm-xilinx-eabi-gcc/vbw_rgb2luma16.o' failed
make[1]: *** [obj/arm-xilinx-eabi-gcc/vbw_rgb2luma16.o] Error 1
../../common/xil_app.mk:149: recipe for target '../../lib/vbxware-recurs-make-lib' failed
make: *** [../../lib/vbxware-recurs-make-lib] Error 2

**Comment by vanjoe** [comment]
I believe I had fixed this in commit  #3fb41f2ff  unfortunately I forgot to update the BSPs for the prebuilt systems. I will do this shortly, in the meantime you could regenerate the BSP.

**Comment by vanjoe** [comment]
Sorry this took so long, but the prebuilt examples should work now.
